from typing import Optional, Tuple

import numpy as np

class KDTree:
    def __init__(self, points: np.ndarray, leafsize: int=..., max_threads: int=..., boxsize: Optional[float]=None) -> None: ...

    def query(self, points: np.ndarray, k: int=1, workers: int=1) -> Tuple[np.ndarray, np.ndarray]: ...

    @property
    def n(self) -> int: ...
    @property
    def size(self) -> int: ...

    @property
    def periodic(self) -> bool: ...
    @property
    def boxsize(self) -> float: ...
