# Interface file for C++ rasterizer bindings.

import numpy as np


class VulkanContainer:
    def __init__(self, enable_validation_layers: bool=...) -> None: ...

class PointRenderer:
    def __init__(self, vulkan_container: VulkanContainer, box_size: float, grid_size: int, subsample_factor: int=...) -> None: ...

    @property
    def grid_size(self) -> int: ...
    @property
    def box_size(self) -> float: ...

    def render_points(self, positions: np.ndarray, weights: np.ndarray, radii: np.ndarray) -> np.ndarray: ...
    def render_points_volume(self, positions: np.ndarray, weights: np.ndarray, radii: np.ndarray) -> np.ndarray: ...
